#!/bin/awk -f
BEGIN	{
	fn = "/usr/share/X11/rgb.txt"
	while( getline < fn > 0 )	{
		sub( /!.*$/, "" )
		if( NF >= 4 )	{
			r = $1
			g = $2
			b = $3
			$1 = $2 = $3 = ""
			sub( /^[ \t]*/, "" )
			sub( /[ \t]*$/, "" )
			color = tolower( $0 )
			colors[ color ] = sprintf( "#%02X%02X%02X", r, g, b )
		}
	}
}
/./	{
	for( i = 1; i <= NF; ++i )	{
		color = tolower( $i )
		if( color in colors )	{
			$i = colors[ color ]
		}
	}
	print
}
END	{
}
